CREATE OR REPLACE VIEW PATIENT_FULL_INFO AS
    SELECT TH.HISTNUMBER AS HISTORYTREATMID, P.PESEL, P.NAME || ' ' || P.SURNAME AS PATIENT, P.PHONENUMBER, P.POSTNUMBER, P.MUNICIPALITY, P.CITY, 
    P.STREET, P.HOMENUMBER, P.APARTMENTNUMBER, P.BIRTHDATE, get_patient_age(P.PESEL) PATIENT_AGE, P.DOCTORID,
    DOC.NAME || ' ' ||DOC.SURNAME AS DOCTOR, SPE.FULLNAME AS SPECIALIZATION,
    P.REGISTRATIONDATE, MDX.EXECDATE, MDX.RESULTDATE, MDX.MEDEXAMNAME, MDX.RESULTS,
    DIA.DIAGDATE, DIA.DESCRIBE AS DIAGNOSIS,
    MDT.EXECDATE AS OPERATION_DATE, MDT.DESCRIBE AS OPERATION_DESCRIBE, TH.DESCRIBE AS HISTORY, 
    DIS.DISCHARGEDATE, DE.DEATHDATE, DE.CAUSE AS DEATHCAUSE, DE.ANNOTATION
    FROM PATIENTS P
    LEFT JOIN DOCTORS DOC ON P.DOCTORID = DOC.PERSONNELNUMBER
    LEFT JOIN SPECIALIZATIONS SPE ON SPE.SHORTCUT = DOC.SPECIALIZATION
    LEFT JOIN MEDEXAMS MDX ON MDX.PESEL = P.PESEL
    LEFT JOIN DIAGNOSIS DIA ON DIA.PESEL = P.PESEL
    LEFT JOIN MEDTREATM MDT ON MDT.PESEL = P.PESEL
    LEFT JOIN TREATMENTHISTORY TH ON TH.PESEL = P.PESEL
    LEFT JOIN DISCHARGES DIS ON DIS.PESEL = P.PESEL
    LEFT JOIN DEATH DE ON DE.PESEL = P.PESEL;