CREATE OR REPLACE VIEW S209312.V_PACJENCI_PELNE_INFO AS
    SELECT TH.NR_HIST AS NR_HISTORII, P.PESEL, P.IMIE || ' ' || P.NAZWISKO AS PACJENT, P.PLEC, P.NR_TELEFONU, P.POCZTA, P.GMINA, P.MIASTO, P.ULICA, 
    P.NR_DOMU, P.NR_MIESZKANIA, S209312.get_birthdate_from_pesel(P.PESEL) AS DATA_URODZENIA, S209312.get_patient_age(P.PESEL) WIEK, 
    P.STATUS, P.LEKARZ AS NRKADR_LEKARZ, DOC.IMIE || ' ' ||DOC.NAZWISKO AS LEKARZ_PROWADZACY, SPE.SPECJALIZACJA,
    P.DATA_REJESTRACJI, MDX.DATA_BADANIA, MDX.DATA_WYNIKOW, MDX.RODZAJ_BADANIA, MDX.WYNIKI,
    DIA.DIAG_DATA, DIA.DIAGNOZA,
    MDT.OPER_DATA AS DATA_ZABIEGU, MDT.OPIS AS OPIS_ZABIEGU, TH.OPIS AS HISTORIA_LEZCZENIA, 
    NVL(DIS1.DATA_WYPISU, DIS2.DATA_WYPISU) AS DATA_WYPSIU, DE.DATA_SMIERCI, DE.PRZYCZYNA AS PRZYCZYNA_SMIERCI
    FROM S209312.PACJENCI P
    LEFT JOIN S209312.lekarze DOC ON P.LEKARZ = DOC.NRKADR
    LEFT JOIN S209312.SPECJALIZACJE SPE ON SPE.SPECID = DOC.SPECID
    LEFT JOIN S209312.BADANIA MDX ON MDX.PESEL = P.PESEL
    LEFT JOIN S209312.DIAGNOZY DIA ON DIA.PESEL = P.PESEL
    LEFT JOIN S209312.OPERACJE MDT ON MDT.PESEL = P.PESEL
    LEFT JOIN S209312.LECZENIE_HIST TH ON TH.PESEL = P.PESEL
    LEFT JOIN S209312.WYPISY_W_PELNI_ZDROWI DIS1 ON DIS1.PESEL = P.PESEL
    LEFT JOIN S209312.WYPISY_DALSZE_LECZENIE DIS2 ON DIS2.PESEL = P.PESEL
    LEFT JOIN S209312.ZGONY DE ON DE.PESEL = P.PESEL;